Feature/os2forms failed jobs
itk-dev/os2forms_selvbetjening pull request #126
Opened 2023-01-27 13:21 UTC by martinyde

2023-01-30 08:36 UTC, rimi-itk requested changes
This is really good. Some comments and suggestions added on minor details.

Should this be a contrib module (under the https://github.com/OS2Forms/ umbrella) rather than a custom module?

2023-01-30 08:36 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/os2forms_failed_jobs.routing.yml
> +    _permission: 'administer advancedqueue'
Do we need more lax permission here to let form designers access this route? I'm not quite sure how powerful the “administer advancedqueue” permission actually is, but the name implies that it should not be granted to form designers.

2023-01-30 08:36 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Controller/Os2formsFailedJobsController.php
> +      $container->get('Drupal\os2forms_failed_jobs\Helper\Os2formsFailedJobsHelper'),
Use `Os2formsFailedJobsHelper::class` here to get the service, i.e.

```php
      …
      $container->get(Os2formsFailedJobsHelper::class),
      …
```

2023-01-30 08:36 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Controller/Os2formsFailedJobsController.php
> +    ];
Can we just return `$view->render()` here? Rendering `$view->render()` and returning the result as `#markup` seems like we're doing some rendering that will (also) be handled elsewhere.

2023-01-30 08:36 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Controller/Os2formsFailedJobsController.php
> +  private function getSubmissionIdsFromForm(string $formId): array {
If this function returns a “List of submission” (cf. `@return`) it should be called `getSubmissionsFromForm` (i.e. without “Id”).

2023-01-30 08:36 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Controller/Os2formsFailedJobsController.php
> +    return $query->execute();
This can be written as 

```php
return $this->entityTypeManager
  ->getStorage('webform_submission')
  ->getQuery()
  ->accessCheck(TRUE)
  ->condition('webform_id', $formId)
  ->execute();
```

which may be a little easier to read.

2023-01-30 08:36 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Form/RetryJob.php
> +      $container->get('Drupal\os2forms_failed_jobs\Helper\Os2formsFailedJobsHelper'),
Use `Os2formsFailedJobsHelper::class` to get the service.

2023-01-30 08:36 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Form/RetryJob.php
> +    $webform = $submission->webform_id->target_id;
Do you skip using `$submission->getWebform()` here for performance reasons?

2023-01-30 09:18 UTC, martinyde commented on web/modules/custom/os2forms_failed_jobs/src/Controller/Os2formsFailedJobsController.php
> +      $container->get('Drupal\os2forms_failed_jobs\Helper\Os2formsFailedJobsHelper'),
Hmm, tried it, and it doesn't seem to work

2023-01-30 09:36 UTC, martinyde commented on web/modules/custom/os2forms_failed_jobs/src/Form/RetryJob.php
> +      $container->get('Drupal\os2forms_failed_jobs\Helper\Os2formsFailedJobsHelper'),
For some reason this fails.

2023-01-30 09:51 UTC, martinyde commented on web/modules/custom/os2forms_failed_jobs/src/Form/RetryJob.php
> +      $queue_backend->deleteJob($this->jobId);
I'm unsure which is better. Releasing the job will not clear the job message in or change the timestamps.

2023-01-30 10:27 UTC, martinyde commented on web/modules/custom/os2forms_failed_jobs/os2forms_failed_jobs.routing.yml
> +    _permission: 'administer advancedqueue'
Yeah, changed to match whoever has access to the failed jobs view

2023-01-30 10:40 UTC, martinyde commented on web/modules/custom/os2forms_failed_jobs/src/Helper/Os2formsFailedJobsHelper.php
> +  public function getJobFromId(int $jobId) {
Changed

2023-01-30 12:52 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Controller/Os2formsFailedJobsController.php
> +      $container->get('Drupal\os2forms_failed_jobs\Helper\Os2formsFailedJobsHelper'),
`Os2formsFailedJobsHelper::class` is the string `'Drupal\os2forms_failed_jobs\Helper\Os2formsFailedJobsHelper'`, i.e. exactly the same, so it works (unless there's a typo or something else lurking in the corners).

2023-01-30 13:11 UTC, rimi-itk requested changes

2023-01-30 13:11 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Helper/Os2formsFailedJobsHelper.php
> +  public function getJobFromId(int $jobId) {
Well, now it returns a `StatementInterface`. Having it return a `Drupal\advancedqueue\Job` will make the code using the return value much cleaner, e.g.

```php
 public function getSubmissionIdFromJob(int $jobId): ?int {
    $job = $this->getJobFromId($jobId);
    if (NULL === $job) {
      return NULL;
    }
    $payload = $job->getPayload();

    return $payload['submissionId'] ?? $payload['submission']['id'] ?? NULL;
  }

2023-01-30 13:11 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/config/install/views.view.os2forms_failed_jobs.yml
> +    - os2forms_failed_jobs
I think we should also have en “enforced dependency” here to make sure that this config is removed if the module is uninstalled (cf. https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-entity-dependencies#s-enforced-dependencies).

2023-02-01 14:16 UTC, martinyde commented on web/modules/custom/os2forms_failed_jobs/src/Controller/Os2formsFailedJobsController.php
> +      $container->get('Drupal\os2forms_failed_jobs\Helper\Os2formsFailedJobsHelper'),
Fixed

2023-02-01 14:20 UTC, martinyde commented on web/modules/custom/os2forms_failed_jobs/src/Controller/Os2formsFailedJobsController.php
> +class Os2formsFailedJobsController extends ControllerBase {
Changed

2023-02-02 14:39 UTC, rimi-itk requested changes

2023-02-02 14:39 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Controller/Controller.php
> +    return $view->render() ?? ['#markup' => $this->t('No failed jobs')];
🎉

2023-02-02 14:39 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Form/RetryJob.php
> +      $job->setPayload(json_decode($job->getPayload(), TRUE));
This should be handled in `getJobFromId()`, i.e. it must create a Job where the payload is already an array.

2023-02-02 14:39 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Helper/Helper.php
> +    return new Job($jobArr);
JSON-decode `$jobArr['payload']` before calling the Job constructor. The payload is expected to be an array (cf. https://git.drupalcode.org/project/advancedqueue/-/blob/8.x-1.x/src/Job.php#L228-249).

2023-02-02 14:39 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Helper/Helper.php
> +    $payload = json_decode($job->getPayload(), TRUE);
See comment on `getJobFromId`.

2023-02-02 14:39 UTC, rimi-itk commented on web/modules/custom/os2forms_failed_jobs/src/Helper/Helper.php
> +    $jobArr = $query->execute()->fetchAssoc();
Don't use Hungarian notation (https://en.wikipedia.org/wiki/Hungarian_notation), i.e. call this variable `$definition`, say (inspired by the name in the Job constructor), without hints on the type (“Arr”).

2023-02-02 14:57 UTC, martinyde commented on web/modules/custom/os2forms_failed_jobs/src/Helper/Helper.php
> +    return new Job($jobArr);
Fixed

2023-02-02 14:57 UTC, martinyde commented on web/modules/custom/os2forms_failed_jobs/src/Helper/Helper.php
> +    $payload = json_decode($job->getPayload(), TRUE);
Fixed

2023-02-02 14:58 UTC, martinyde commented on web/modules/custom/os2forms_failed_jobs/src/Helper/Helper.php
> +    $jobArr = $query->execute()->fetchAssoc();
Fixed

2023-02-02 15:01 UTC, rimi-itk approved these changes

2023-02-03 12:39 UTC, closed without merging

2023-02-03 12:39 UTC, martinyde commented
Added through composer instead