feature/DW 411 access by permisisons by term
itk-dev/os2forms_selvbetjening pull request #14
Opened 2021-11-26 10:24 UTC by martinyde

- DW-411: Added gitignore
- DW-411: Added os2forms_webform_list module
- DW-411: Added os2forms_permissions_by_term module

2021-11-26 11:08 UTC, rimi-itk requested changes

2021-11-26 11:08 UTC, rimi-itk commented on web/modules/custom/os2forms_webform_list/src/customWebformEntityListBuilder.php
> +    $query->condition('id', $webform_ids_permissions_by_term, 'IN');
You should have only these lines plus a call to `parent::getQuery()` in your implementation of `getQuery`, i.e.

```php
  protected function getQuery($keys = '', $category = '', $state = '') {
    $query = parent::getQuery($keys, $category, $state);

    // Setup a required condition for the list builder to respect webform update access.
    …

    return $query;
  }
```

2021-11-26 11:08 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +        }
Should be written as 

```php
return empty($webformPermissionsByTerm) || !empty(array_intersect($webformPermissionsByTerm, $userTerms)
  ? AccessResult::neutral()
  : AccessResult::forbidden();
```

2021-11-26 11:08 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +        break;
Don't use `break` after `return`.

2021-11-26 12:59 UTC, martinyde commented on web/modules/custom/os2forms_webform_list/os2forms_webform_list.module
> +  $entity_types['webform']->setListBuilderClass('Drupal\os2forms_webform_list\customWebformEntityListBuilder');
The proposed change results in :
`Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException: The "webform" entity type did not specify a  
                                                list_builder handler. in Drupal\Core\Entity\EntityTypeManager->getHandler() `

2021-11-26 13:07 UTC, rimi-itk commented on web/modules/custom/os2forms_webform_list/os2forms_webform_list.module
> +  $entity_types['webform']->setListBuilderClass('Drupal\os2forms_webform_list\customWebformEntityListBuilder');
Apparently, I assume that `customWebformEntityListBuilder` has been renamed to `CustomWebformEntityListBuilder` …

2021-11-29 08:49 UTC, martinyde commented on web/modules/custom/os2forms_webform_list/src/customWebformEntityListBuilder.php
> +class customWebformEntityListBuilder extends WebformEntityListBuilder {
Fixed

2021-11-29 08:49 UTC, martinyde commented on web/modules/custom/os2forms_webform_list/src/customWebformEntityListBuilder.php
> +    $query->condition('id', $webform_ids_permissions_by_term, 'IN');
Fixed

2021-11-29 08:49 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +        break;
Fixed

2021-11-29 08:49 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +        }
Fixed

2021-11-29 08:50 UTC, martinyde commented on web/modules/custom/os2forms_webform_list/os2forms_webform_list.module
> +  $entity_types['webform']->setListBuilderClass('Drupal\os2forms_webform_list\customWebformEntityListBuilder');
Wont fix

2021-11-29 09:13 UTC, rimi-itk requested changes

2021-11-29 09:13 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +      '#default_value' => 'settings' === $hook ? $defaultSettings : [],
Using `'#default_value' => $defaultSettings ?? []` here will make more sense (to me) as `$defaultSettings` is set only if `'settings' === $hook` (cf. line 86–90.

Alternatively, add `$defaultSettings = []` in line 85 and use `'#default_value' => $defaultSettings` here.

2021-11-29 09:35 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +      '#default_value' => 'settings' === $hook ? $defaultSettings : [],
Fixed

2021-11-29 09:36 UTC, rimi-itk approved these changes

2021-11-30 11:10 UTC, merged