Feature/maestro templates permissions by term
itk-dev/os2forms_selvbetjening pull request #16
Opened 2021-12-09 20:42 UTC by martinyde

Adds permission by term to maestro templates and removes the templates from the list if not permitted to see them.

2021-12-10 10:57 UTC, lats1 commented
Before I review this pull request. Is this specific for our instance of the solution or should it actually be put on one the "official" parts e.g. the module or profile?

2021-12-10 10:58 UTC, lats1 requested changes
Before I review this pull request. Is this specific for our instance of the solution or should it actually be put on one the "official" parts e.g. the module or profile?

2021-12-13 11:02 UTC, martinyde commented
> Before I review this pull request. Is this specific for our instance of the solution or should it actually be put on one the "official" parts e.g. the module or profile?

For now i think it's specific to our instance, but i have a separate issue to share this to the os2forms project when it has been tested and is ready

2021-12-16 11:45 UTC, rimi-itk reviewed
Just some comments and questions.

2021-12-16 11:45 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module
> +function os2forms_permissions_by_term_form_webform_add_form_alter(array &$form, FormStateInterface $form_state) {
Are you removing the `$form_id` because you don't need/use it? As per https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Form%21form.api.php/function/hook_form_FORM_ID_alter/8.9.x it is still a part of the parameters sent to `hook_form_FORM_ID_alter`.

2021-12-16 11:45 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module
> +  \Drupal::service('os2forms_permissions_by_term.maestro_template_helper')->maestroTemplateFormAlter($form, $form_state, 'settings');
Should `'settings'` be `'edit'` here (to match “…maestro_template_*edit*_form_alter”)?

2021-12-16 11:45 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +   * @return mixed The resulting access permission.
👍

2021-12-16 11:45 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/MaestroTemplateHelper.php
> +      $form['maestro_template_permissions_by_term']['os2forms_access']['#value'] = [array_key_first($term_data) => array_key_first($term_data)];
This is the first use of `array_key_first` I've seen for real. I like it!

2021-12-16 11:45 UTC, rimi-itk commented on web/modules/custom/os2forms_webform_list/src/CustomMaestroTemplateEntityListBuilder.php
> +    }
I'm not sure where this is used and I suppose you know what you're doing, but this may conflict with sorting and pagination if stuff like that is used on the list display.

2021-12-16 12:10 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module
> +function os2forms_permissions_by_term_form_webform_add_form_alter(array &$form, FormStateInterface $form_state) {
Yeah, we could leave it but there is not much point i think

2021-12-16 12:14 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module
> +  \Drupal::service('os2forms_permissions_by_term.maestro_template_helper')->maestroTemplateFormAlter($form, $form_state, 'settings');
Could be, but it's very similar to os2forms_permissions_by_term_form_webform_settings_form_alter that uses the settings naming when editing a form config entity

2021-12-16 12:16 UTC, martinyde commented on web/modules/custom/os2forms_webform_list/src/CustomMaestroTemplateEntityListBuilder.php
> +    }
Hmm, i'll takte note of that, we will have to follow up

2021-12-16 12:16 UTC, merged