Feature/OIDC to term
itk-dev/os2forms_selvbetjening pull request #18
Opened 2021-12-14 13:55 UTC by martinyde

- Config for new taxonomy (oidc_user_affiliation) and related fields 
 - Enable os2forms permissions by term in config
 - Change COMPOSE_PROJECT_NAME
 - Combine OIDC to oidc_user_affiliation taxonomy

2021-12-14 14:15 UTC, rimi-itk requested changes
Looks good and I suppose it works. However, I have two requests:

We should not use the terms `oidc` or `office` anywhere. This should work regardless of what the authentication mechanism is called and what claim/property were using to give permissions.

Renaming the taxonomy vocabulary to `user_affiliation` and the field to `field_user_affiliation` will make the solution more general, and then we also need some configuration to tell us that we should look for `$context['user_data']['Office']`.

2021-12-14 14:15 UTC, rimi-itk commented on web/modules/custom/itkdev_openid_connect/itkdev_openid_connect.module
> +  * @todo Add to Helper service class.
👍

2021-12-14 14:15 UTC, rimi-itk commented on web/modules/custom/itkdev_openid_connect/src/Helper/Helper.php
> +    $terms =\Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
Use `$this->entityTypeManager` here.

2021-12-14 14:15 UTC, rimi-itk commented on config/sync/core.entity_form_display.node.webform.default.yml
> +    - workflows.workflow.udgivelse_af_forlob_og_webformularer
Where does this come from? `workflows.workflow.udgivelse_af_forlob_og_webformularer` does not seem to be created in this pull request.

2021-12-14 14:15 UTC, rimi-itk commented on web/modules/custom/itkdev_openid_connect/src/Helper/Helper.php
> +      if (isset($office) && $office === $context['user_data']['Office']) {
We should able to handle a list of values in the claim (`$context['user_data']['Office']`).

2021-12-14 15:06 UTC, martinyde commented on web/modules/custom/itkdev_openid_connect/src/Helper/Helper.php
> +      if (isset($office) && $office === $context['user_data']['Office']) {
I think this was exposed as a string in my tests "ITK Development" for my@aarhus.dk, are you implying it could also be of type array?

2021-12-14 16:12 UTC, rimi-itk commented on web/modules/custom/itkdev_openid_connect/src/Helper/Helper.php
> +      if (isset($office) && $office === $context['user_data']['Office']) {
We don't know if `Office` is the claim we'll actually use for this, but for now it's our best guess. However, we should be able to handle a list of values to put users into multiple taxonomies (in the future).

Casting a scalar to an array will create an array with a single value, i.e. we can do something like

```php
$claim = 'Office'; // ???
$values = (array)$context['user_data'][$claim];
foreach ($values as $value) {
  // Find taxonomy term and add to user
}
```

2021-12-15 11:55 UTC, martinyde commented on web/modules/custom/itkdev_openid_connect/src/Helper/Helper.php
> +      if (isset($office) && $office === $context['user_data']['Office']) {
Changed

2021-12-15 14:08 UTC, martinyde commented
A changed naming and  stuff in comments and made it more generic. I'm unsure why you want configuration for $context['user_data'] in a module prefixed itkdev and seemingly very specific to os2forms.

2021-12-16 06:10 UTC, rimi-itk approved these changes

2021-12-16 06:14 UTC, rimi-itk commented
Your point about the module name (`itkdev_…`) is really good. We/I should rename it to `os2forms_selvbetjening_user` or something similar.

2021-12-16 06:14 UTC, merged