Updated README installation
itk-dev/os2forms_selvbetjening pull request #271
Opened 2024-01-18 15:36 UTC by jekuaitk

Updates `README` with missing network

2024-01-18 16:39 UTC, rimi-itk requested changes

2024-01-18 16:39 UTC, rimi-itk commented on README.md
> +
I think you should move this outside the code block and put it just under the “Installation” heading and write something along the lines of

> The development setup depends on the `serviceplatformen_organisation_api_app` network which is used to access the API from <https://github.com/itk-dev/serviceplatformen_organisation_api>. If you start that project (cf. [Getting started](https://github.com/itk-dev/serviceplatformen_organisation_api/blob/develop/README.md#getting-started)), you're good to go. If you don't need the API during development, you can manually create the network by running

```sh
docker network create serviceplatformen_organisation_api_app
```

2024-01-18 20:11 UTC, jekuaitk commented on README.md
> +
Updated.

2024-01-19 09:18 UTC, rimi-itk approved these changes

2024-01-19 09:19 UTC, merged