Release 2.7.5
itk-dev/os2forms_selvbetjening pull request #276
Opened 2024-01-25 15:41 UTC by jekuaitk

https://leantime.itkdev.dk/#/tickets/showTicket/526

* #526: Add logout link to flow page

2024-01-25 16:03 UTC, rimi-itk requested changes

2024-01-25 16:03 UTC, rimi-itk commented on web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
> +            $form['error']['#markup'] = $this->t('You do not have access to this task. The task has either been reassigned or is no longer valid. Here is a suggestion to what you can do. Try <a href=
Consider keeping the original error message and append your own, e.g. something like

```suggestion
            $form['error'] = [
              '#type' => 'container',
              'error_message' => $form['error'] + [
                '#prefix' => '<div>',
                '#sufix' => '</div>',
              ],
              'suggestion' => [
                '#markup' = $this->t('Here is a suggestion to what you can do. Try <a href=":url">logging out</a>.', [':url' => $logoutUrl]),
                '#prefix' => '<div>',
                '#sufix' => '</div>',
              ],
            ];              
```

2024-01-25 16:03 UTC, rimi-itk commented on web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
> +      if (isset($form['error']['#markup'])) {
Consider combining to 

```suggestion
    if ('maestro_interactive_form' === $form_id && isset($form['error']['#markup'])) {
```

2024-01-25 16:03 UTC, rimi-itk commented on web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
> +    if ('maestro_interactive_form' === $form_id) {
You're missing a check for a user currently being authenticated.

2024-01-26 09:04 UTC, jekuaitk commented on web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
> +          if ('You do not have access to this task.  The task has either been reassigned or is no longer valid.' === $markup->getUntranslatedString()) {
Good idea. Updated.

2024-01-26 09:05 UTC, jekuaitk commented on web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
> +      if (isset($form['error']['#markup'])) {
Combined.

2024-01-26 09:26 UTC, jekuaitk commented on web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
> +    if ('maestro_interactive_form' === $form_id) {
Good catch. Added check for current user being logged in.

2024-01-26 09:26 UTC, jekuaitk commented on web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
> +            $form['error']['#markup'] = $this->t('You do not have access to this task. The task has either been reassigned or is no longer valid. Here is a suggestion to what you can do. Try <a href=
Good idea. Updated.

2024-01-26 11:41 UTC, rimi-itk requested changes

2024-01-26 11:41 UTC, rimi-itk commented on web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
> +    if ('maestro_interactive_form' === $form_id && isset($form['error']['#markup']) && $this->account->isAuthenticated()) {
I little note on what we're doing here (and maybe why) would be nice.

2024-01-26 11:41 UTC, rimi-itk commented on web/themes/custom/os2forms_selvbetjening_theme/templates/page/page--4xx.html.twig
> +      {{ 'Here is a suggestion to what you can do. Try <a id="logout_suggestion" href=":url">logging out</a>.'|t({':url': url}) }}
After this change we could remove https://github.com/itk-dev/os2forms_selvbetjening/blob/835a9eea1484cf60ad8da02b14620c929564b008/web/themes/custom/os2forms_selvbetjening_theme/os2forms_selvbetjening_theme.theme#L10 but `site_name` may come in handy later, so it may make sense to just keep it.

2024-01-26 11:46 UTC, jekuaitk commented on web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
> +    if ('maestro_interactive_form' === $form_id && isset($form['error']['#markup']) && $this->account->isAuthenticated()) {
Added comment.

2024-01-26 11:55 UTC, rimi-itk approved these changes

2024-01-29 08:07 UTC, merged