#1039: Added Maestro notification pdf template
itk-dev/os2forms_selvbetjening pull request #291
Opened 2024-03-27 08:38 UTC by jekuaitk

https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/1039

* Adds template with header and colophon to be used in Maestro notifications

Before (default template)
<img width="853" alt="Screenshot 2024-03-27 at 09 38 18" src="https://github.com/itk-dev/os2forms_selvbetjening/assets/78410897/4313c871-4f47-4a2d-abaf-ae9046906005">

After (added template)
<img width="853" alt="Screenshot 2024-03-27 at 09 35 52" src="https://github.com/itk-dev/os2forms_selvbetjening/assets/78410897/36128031-b753-4bbd-a69f-4f32f1be88db">

2024-03-27 13:45 UTC, rimi-itk requested changes

2024-03-27 13:45 UTC, rimi-itk commented on CHANGELOG.md
> +  notifikationer i `os2forms_selvbetjening_theme` temaet.
```suggestion
* Tilføjede templates til ændring af `os2forms_attachment` og maestro-pdf-notifikationer i `os2forms_selvbetjening_theme`-temaet.
```

2024-03-27 13:45 UTC, rimi-itk commented on web/themes/custom/os2forms_selvbetjening_theme/README.md
> +unchecking `Enable Default CSS` on `admin/config/content/entityprint`.
This must be done in our exported config (in `config/sync`).

2024-03-27 13:45 UTC, rimi-itk commented on web/themes/custom/os2forms_selvbetjening_theme/README.md
> +```
This must be done in our exported config (in `config/sync`).

2024-03-27 13:45 UTC, rimi-itk commented on web/themes/custom/os2forms_selvbetjening_theme/assets/pdf.css
> +  margin: 180px 35px 150px 35px;
I think we should set the page size to A4:

```suggestion
  size: A4;
  margin: 180px 35px 150px 35px;  
```

Using `px` seems weird for PDF generation. Do we know how long `1 px` actually is (in `mm`, say) when generating a PDF?

2024-03-27 13:45 UTC, rimi-itk commented on web/themes/custom/os2forms_selvbetjening_theme/templates/pdf/os2forms-selvbetjening-maestro-notification-pdf-html.html.twig
> +          <p>[webform_submission:completed:custom:d. F Y]</p>
Does the `webform_submission:completed` token actually exist when rendering a notification for real? Using the current time may be more appropriate.

2024-04-02 07:17 UTC, jekuaitk commented on web/themes/custom/os2forms_selvbetjening_theme/templates/pdf/os2forms-selvbetjening-maestro-notification-pdf-html.html.twig
> +          <p>[webform_submission:completed:custom:d. F Y]</p>
With https://github.com/OS2Forms/os2forms/pull/95, all Maestro notification content is tokenized.

2024-05-14 10:52 UTC, jekuaitk commented
Moved to https://github.com/itk-dev/os2forms_selvbetjening/pull/315

2024-05-14 10:52 UTC, closed without merging