1584: Updated email handler allowing file size notification
itk-dev/os2forms_selvbetjening pull request #319
Opened 2024-06-05 13:06 UTC by jekuaitk

https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1584

* Updates email handler
  * Added email notifications based on attachment file size

2024-06-06 08:23 UTC, rimi-itk requested changes

2024-06-06 08:23 UTC, rimi-itk commented on web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +      $emailAddress = trim($emailAddress);
Do this like you usually do it, i.e. like https://github.com/itk-dev/naevnssekretariatet/blob/develop/src/Service/BoardHelper.php#L22.

2024-06-06 08:23 UTC, rimi-itk commented on web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +      return $type === $element['#type'];
Not all form elements have a `#type` key (we've struggled with this before):

```suggestion
      return $type === ($element['#type'] ?? NULL);
```

2024-06-06 08:23 UTC, rimi-itk commented on web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +  private function getAvailableElementsByType(string $type, array $elements): array {
Why is “Available” part of the function name? Which elements are “not available”?

```suggestion
  private function getElementsByType(string $type, array $elements): array {
```

2024-06-06 08:23 UTC, rimi-itk commented on web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +  private function isAttachmentFileSizeThresholdSurpassed(WebformSubmissionInterface $webform_submission): bool {
Consider adding a function getting the total size of all attachments, `getTotalAttachmentFileSize`, say, and the just call this to check if the limit is surpassed. Being able to get the total size may come in handy later.

2024-06-06 08:23 UTC, rimi-itk commented on web/modules/custom/os2forms_email/os2forms_email.info.yml
> +description: 'Overrides email handler adding extra checks and functionality'
In this case, I suggest calling the module `os2form_email_handler`.

2024-06-06 08:23 UTC, rimi-itk commented on web/modules/custom/os2forms_email/os2forms_email.info.yml
> +core_version_requirement: ^9
Work is in progress to upgrade OS2Forms to Drupal 10:

```suggestion
core_version_requirement: ^9 || ^10
```

2024-06-06 08:23 UTC, rimi-itk commented on web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +    $fileElements = array_merge(...$fileElements);
Array functions are your friend (you've already used them at least twice in this pull request):

```suggestion
    $fileElements = array_map(
      fn ($type) => $this->getAvailableElementsByType($type, $elements),
      self::FILE_ELEMENT_TYPES
    );

    // Flatten the array.
    // https://dev.to/klnjmm/never-use-arraymerge-in-a-for-loop-in-php-5go1
    $fileElements = array_merge(...$fileElements);
```

2024-06-06 08:23 UTC, rimi-itk commented on web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +    }
Consider using https://www.php.net/manual/en/function.array-reduce.php here.

2024-06-06 08:23 UTC, rimi-itk commented on web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +        'link' => ($webform_submission->id()) ? $webform_submission->toLink($this->t('View'))->toString() : NULL,
```suggestion
        'link' => $webform_submission->id() ? $webform_submission->toLink($this->t('View'))->toString() : NULL,
```

2024-06-06 08:39 UTC, jekuaitk commented on web/modules/custom/os2forms_email/os2forms_email.info.yml
> +description: 'Overrides email handler adding extra checks and functionality'
Good idea.

2024-06-06 08:48 UTC, jekuaitk commented on web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +  private function getAvailableElementsByType(string $type, array $elements): array {
Renamed.

2024-06-06 08:49 UTC, jekuaitk commented on web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +  private function getRelevantFileIdsFromSubmission(WebformSubmissionInterface $submission): array {
I added `Relevant` since it filters out file elements that have been excluded in the email handler.

Renamed.

2024-06-06 09:01 UTC, jekuaitk commented on web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +      $emailAddress = trim($emailAddress);
Updated.

2024-06-06 11:43 UTC, rimi-itk commented on README.md
> +$config['os2forms_email_handler']['notification_message_from_name'] = 'Selvbetjening';
Do we really need to use config for this? Using settings, i.e. `$settings['os2forms_email_handleros2forms_email_handler'][…] = …` and `Settings::get`, may be much easier.

`$config` in `settings.local.php` is used to override config, but we're not overriding anything, but _setting_ something.

2024-06-06 11:43 UTC, rimi-itk commented on web/modules/custom/os2forms_email_handler/src/Helper/WebformHelper.php
> +    $defaultValues = $webform->getThirdPartySetting('os2forms', 'os2forms_email_handler');
Having the string `os2forms_email_handler` in a (public) `const` may help clean up things (and make it easier to refactor if needed).

2024-06-06 11:43 UTC, rimi-itk commented on web/modules/custom/os2forms_email_handler/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +    $unitExponentMultiplier = ((int) array_search($unit, $units)) + 1;
Did you come up with this yourself? There's nothing wrong with stealing/borrowing/copying code, but if a bug appears, having a source reference like <https://stackoverflow.com/questions/11807115/php-convert-kb-mb-gb-tb-etc-to-bytes>, say, may be handy to fix the issue.

2024-06-06 11:43 UTC, rimi-itk commented on web/modules/custom/os2forms_email_handler/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +    });
👍

2024-06-06 12:59 UTC, jekuaitk commented on README.md
> +$config['os2forms_email_handler']['notification_message_from_name'] = 'Selvbetjening';
We do not. Switched to settings.

2024-06-06 13:22 UTC, jekuaitk commented on web/modules/custom/os2forms_email_handler/src/Helper/WebformHelper.php
> +    $defaultValues = $webform->getThirdPartySetting('os2forms', 'os2forms_email_handler');
Added consts.

2024-06-06 13:26 UTC, jekuaitk commented on web/modules/custom/os2forms_email_handler/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +    $unitExponentMultiplier = ((int) array_search($unit, $units)) + 1;
Inspiration was indeed taken from that thread. Added reference to it.

2024-06-07 08:00 UTC, rimi-itk requested changes

2024-06-07 08:00 UTC, rimi-itk commented on web/modules/custom/os2forms_email_handler/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
> +    $settings = Settings::get('os2forms_email_handler');
```suggestion
    $settings = Settings::get(WebformHelper::MODULE_NAME);
```

2024-06-07 10:30 UTC, rimi-itk approved these changes

2024-09-02 13:18 UTC, rimi-itk approved these changes

2024-09-02 13:18 UTC, merged