Added changes to os2forms_permissions_by_term
itk-dev/os2forms_selvbetjening pull request #32
Opened 2022-03-11 09:50 UTC by martinyde

https://jira.itkdev.dk/browse/DW-452 - Node access for anonymous users based on referenced webform
https://jira.itkdev.dk/browse/DW-453 - Limit webform options and group options on node based on user groups.
https://jira.itkdev.dk/browse/DW-457 - Remove access to submission overview page
https://jira.itkdev.dk/browse/DW-459 - User access control on maestro flows

2022-03-11 12:07 UTC, rimi-itk requested changes
Looks good. Some suggestions on cleaning up the code and make it easier to understand added.

2022-03-11 12:07 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.services.yml
> -
Having a blank line above service definitions makes the file a little easier to read.

2022-03-11 12:07 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +          $anonymousUser = User::getAnonymousUser();
These two should be moved outside the `foreach` loop.

2022-03-11 12:07 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +   * Alter the field webform_entity_reference widget.
A comment on why we're doing this could be useful.

2022-03-11 12:07 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +   * Change options list field for node.field_os2forms_permissions.
A comment on why we're doing this could be useful.

2022-03-11 12:07 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/MaestroTemplateHelper.php
> +   * Alter the field webform_entity_reference widget.
A comment on why we're doing this could be useful.

2022-03-11 12:07 UTC, rimi-itk commented on web/modules/custom/os2forms_permissions_by_term/src/Routing/RouteSubscriber.php
> +  }
A comment on what we're doing here and why could be useful.

2022-03-17 07:58 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module
> + * We need the hook_options_list_alter() in this module to trigger after the one in permissions_by_term module.
So did I, but that apparently that is not so.

2022-03-17 08:52 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +          $anonymousUser = User::getAnonymousUser();
Fixed

2022-03-17 08:52 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.services.yml
> -
Fixed

2022-03-17 09:02 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
> +   * Change options list field for node.field_os2forms_permissions.
Added

2022-03-17 09:09 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/src/Routing/RouteSubscriber.php
> +  }
Added

2022-03-17 09:19 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module
> +  if ('node.field_os2forms_permissions' == $context['fieldDefinition']->getFieldStorageDefinition()->id()) {
Moved

2022-03-17 09:19 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module
> +  if ('template_edit_task' == $form_id) {
Moved

2022-03-17 09:20 UTC, martinyde commented on web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module
> +    }
Moved

2022-03-17 09:29 UTC, rimi-itk approved these changes

2022-03-17 09:39 UTC, merged