DW-479: Add GetOrganized module
itk-dev/os2forms_selvbetjening pull request #35
Opened 2022-04-01 12:43 UTC by jekuaitk

* Adds GetOrganized module including a handler for journalizing responses

https://jira.itkdev.dk/browse/DW-479

2022-04-01 14:46 UTC, rimi-itk requested changes
Very good. Some minors changes (and one major) requested.

2022-04-01 14:46 UTC, rimi-itk commented on README.md
> +$config['get_organized'] = [
Your module is called `os2forms_get_organized` so the config should set as `$config['os2forms_get_organized']`.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Helper/WebformHelper.php
> +
Remove this blank line.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Helper/WebformHelper.php
> +    $baseUrl = \Drupal::config('get_organized')->get('base_url');
Use dependency injection to get the config into this class. Hint: Inject a `ConfigFactoryInterface` and set `$this->config` in the contructor.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> + *   id = "get_organized",
Use the module name (`os2forms_get_organized`) in the plugin id.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +      '#default_value' => $this->configuration['case_id'],
Use `??` to prevent errors if `$this->configuration['case_id']` is not set.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +      '#default_value' => $this->configuration['attachment_element'],
Always make sure to handle the case when the key may not be set (hint: `??`).

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +    ];
Do we really want this? We have better ways of debugging.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +  }
Remove these empty functions.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +    }
What is going on here? I think this function should be removed.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +  }
Remove these.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +      throw new AttachmentElementNotFoundException();
Will throwing this exception prevent the user from submitting the form?

Maybe `postSave` should just add a task to a queue (e.g. using https://www.drupal.org/project/advancedqueue) and then the task can be processed later by server cron job. This will make the system more resilient to any errors in the actual journalization code.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +  }
Remove.

2022-04-01 14:46 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +  }
https://www.php.net/manual/en/function.array-filter.php is your friend!

2022-04-04 10:19 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +  }
Refactored to use `array_filter` and `array_map`.

2022-04-04 10:19 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +  }
Removed.

2022-04-04 10:19 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +  }
Removed.

2022-04-04 10:20 UTC, jekuaitk commented on README.md
> +$config['get_organized'] = [
Updated.

2022-04-04 10:20 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Helper/WebformHelper.php
> +
Removed.

2022-04-04 10:20 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Helper/WebformHelper.php
> +    $baseUrl = \Drupal::config('get_organized')->get('base_url');
Injected `ConfigFactoryInterface`.

2022-04-04 10:20 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> + *   id = "get_organized",
Updated.

2022-04-04 10:21 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +      '#default_value' => $this->configuration['attachment_element'],
Used null coalescing operator.

2022-04-04 10:21 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +    ];
Removed debug stuff.

2022-04-04 10:21 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +  }
Removed.

2022-04-04 10:22 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +    }
Removed.

2022-04-06 09:41 UTC, rimi-itk requested changes
Some code refactoring needed.

2022-04-06 09:41 UTC, rimi-itk commented on README.md
> +  'base_url' => '…/_goapi',
I think this url should leave out `/_goapi` (cf. https://github.com/itk-dev/getorganized-api-client-php/blob/develop/src/Service/Documents.php#L15).

2022-04-06 09:41 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Helper/ArchiveHelper.php
> +  public function archive(array $payload)
This `archive` function is closely connected to a queue job and not really useable without a queue job. I think you should change it to accept a WebformSubmission (id) and then put all logic for getting the actual pdf and stuff inside the `archive` function:

```php
public function archive($submissionId) {
  $submission = $this->getSubmission($submissionId);
  …
}
```

This will make the function more useful for other usecases, e.g. from a Drush command to manually archive a submissions.

2022-04-06 09:41 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
>      file_put_contents($tempFile, $fileContent);
You cannot be sure that this temporary file actually exists when the job is processed. You should only store enough information, i.e. the submission id,  in the job payload to be able to actually perform the task when the job is processed.

2022-04-06 12:39 UTC, jekuaitk commented on README.md
> +  'base_url' => '…/_goapi',
Good catch - removed.

2022-04-06 12:41 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Helper/ArchiveHelper.php
> +  public function archive(array $payload)
Refactored module. Now the only thing passed to the queue as payload is `$submissionId` and the handler configuration.

2022-04-06 12:42 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
>      file_put_contents($tempFile, $fileContent);
Good point - refactored as much logic as possible into the `process()` method in the `ArchiveDocument` job.

2022-04-06 14:50 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Helper/ArchiveHelper.php
> +    $fileContent = $elementInfo::getFileContent($element, $submission);
Why do you create an instance and then call a static function on it? Couldn't you just call `WebformEntityPrintAttachment::getFileContent` statically?

2022-04-06 14:56 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +  {
The Drupal coding standards (https://www.drupal.org/docs/develop/standards) states that “Opening brace should be on the same line as the declaration”.

You can check the code with 

```sh
./vendor/bin/phpcs --standard=Drupal web/modules/custom/os2forms_get_organized
```

and apply (some) coding standards with

```sh
./vendor/bin/phpcbf --standard=Drupal web/modules/custom/os2forms_get_organized
```

And we should set up GitHub actions to do this in another pull request.

2022-04-06 16:46 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Helper/ArchiveHelper.php
> +    $fileContent = $elementInfo::getFileContent($element, $submission);
Yes, fixed.

2022-04-06 16:52 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +  {
Just as i got used to Symfony coding standards 😅

Applied coding standards.

2022-04-06 18:29 UTC, rimi-itk approved these changes

2022-04-07 07:14 UTC, merged