DW-535: Added API request handler
itk-dev/os2forms_selvbetjening pull request #44
Opened 2022-05-09 15:35 UTC by rimi-itk

https://jira.itkdev.dk/browse/DW-535

Adds a simple webform handler that sends webform id and submission uuid to an API endpoint.

2022-05-10 09:27 UTC, jekuaitk requested changes

2022-05-10 09:27 UTC, jekuaitk commented on web/modules/custom/os2forms_api_request_handler/src/Plugin/AdvancedQueue/JobType/PostSubmission.php
> +
Remove this.

2022-05-10 09:27 UTC, jekuaitk commented on web/modules/custom/os2forms_api_request_handler/src/Plugin/AdvancedQueue/JobType/PostSubmission.php
> + * Archive document job.
Needs an update.

2022-05-10 09:27 UTC, jekuaitk commented on web/modules/custom/os2forms_api_request_handler/src/Plugin/AdvancedQueue/JobType/PostSubmission.php
> +   * Processes the ArchiveDocument job.
Needs an update.

2022-05-10 09:27 UTC, jekuaitk commented on web/modules/custom/os2forms_api_request_handler/src/PostHelper.php
> +   * Constructs an ArchiveHelper object.
Needs an update.

2022-05-10 09:27 UTC, jekuaitk commented on web/modules/custom/os2forms_api_request_handler/src/PostHelper.php
> +        'sender' => $this->generateUrl('<front>'),
`<front>` looks like a funny route name, is it perhaps some shortcut or something?

2022-05-10 10:01 UTC, rimi-itk commented on web/modules/custom/os2forms_api_request_handler/src/PostHelper.php
> +        'sender' => $this->generateUrl('<front>'),
https://github.com/drupal/drupal/blob/9.5.x/core/modules/system/system.routing.yml#L394-L399

2022-05-10 10:16 UTC, jekuaitk approved these changes

2022-05-10 10:34 UTC, martinyde approved these changes

2022-05-11 09:16 UTC, jekuaitk approved these changes

2022-05-11 09:17 UTC, merged