DW-541: Add option to get documents finalized in GetOrganized
itk-dev/os2forms_selvbetjening pull request #55
Opened 2022-06-16 08:37 UTC by jekuaitk

* Adds option to finalize (journalisere) documents archived in GetOrganized

https://jira.itkdev.dk/browse/DW-541

2022-06-18 10:28 UTC, rimi-itk requested changes

2022-06-18 10:28 UTC, rimi-itk commented on composer.json
> +        "itk-dev/getorganized-api-client-php": "^1.0",
👍

2022-06-18 10:28 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Helper/ArchiveHelper.php
> +    $shouldBeFinalized = $handlerConfiguration['should_be_finalized'];
You should use `$shouldBeFinalized = $handlerConfiguration['should_be_finalized'] ?? FALSE;` here to prevent requesting a key that does not exist. The configuration for existing form handlers will not have the `should_be_finalized` key.

2022-06-18 10:28 UTC, rimi-itk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +      '#description' => $this->t("If enabled, documents will be finalized (journaliseret) in GetOrganized."),
Use single quotes (`'…'`) here.

2022-06-20 06:19 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Helper/ArchiveHelper.php
> +    $shouldBeFinalized = $handlerConfiguration['should_be_finalized'];
Good catch!

2022-06-20 06:19 UTC, jekuaitk commented on web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
> +      '#description' => $this->t("If enabled, documents will be finalized (journaliseret) in GetOrganized."),
Fixed.

2022-06-20 06:50 UTC, rimi-itk approved these changes

2022-06-20 06:53 UTC, merged