DW-585: Updated file api endpoint access logic
itk-dev/os2forms_selvbetjening pull request #75
Opened 2022-08-25 10:35 UTC by jekuaitk

https://jira.itkdev.dk/browse/DW-585

* Updates file API endpoint access login in OS2Forms Rest API module

2022-08-25 10:59 UTC, rimi-itk requested changes

2022-08-25 10:59 UTC, rimi-itk commented on web/modules/custom/os2forms_rest_api/src/WebformHelper.php
> +        $settings = $webform->getThirdPartySetting('os2forms', 'os2forms_rest_api');
`$webform` may be `null` here.

2022-08-25 10:59 UTC, rimi-itk commented on web/modules/custom/os2forms_rest_api/src/WebformHelper.php
> +      }
Why do you handle administrators in a special way? Shouldn't they be treated like all other users?

2022-08-25 10:59 UTC, rimi-itk commented on web/modules/custom/os2forms_rest_api/README.md
> +> curl --silent --header 'api-key: …' https://127.0.0.1:8000/entity/file/some_document_id
It seems weird that/if this url has suddenly changed. Has the old url never worked? Why has it changed?

2022-08-25 11:04 UTC, jekuaitk commented on web/modules/custom/os2forms_rest_api/README.md
> +> curl --silent --header 'api-key: …' https://127.0.0.1:8000/entity/file/some_document_id
The actual url to use for the call has not changed. 

It was documented correct [table](https://github.com/itk-dev/os2forms_selvbetjening/blob/develop/web/modules/custom/os2forms_rest_api/README.md?plain=1#L28), but in the example `/webform_rest` had been added by mistake.

2022-08-30 08:11 UTC, jekuaitk commented on web/modules/custom/os2forms_rest_api/src/WebformHelper.php
> +        $settings = $webform->getThirdPartySetting('os2forms', 'os2forms_rest_api');
Used the event approach instead.

2022-08-30 08:12 UTC, jekuaitk commented on web/modules/custom/os2forms_rest_api/src/WebformHelper.php
> +      }
Used Event approach instead.

2022-08-30 09:27 UTC, rimi-itk requested changes
Looks good. Some minor changes requested.

In general we're not modifying the data *received* from the API endpoint, but the data *sent* from the endpoint.

2022-08-30 09:27 UTC, rimi-itk commented on web/modules/custom/os2forms_rest_api/src/EventSubscriber/WebformSubmissionEventSubscriber.php
> +        $values = (array) $data[$name];
A comment telling why we cast to an `array` here (and why it works) may be handy.

2022-08-30 09:27 UTC, rimi-itk commented on composer.json
> +                "Add ability to modify data received the Webform Submission endpoint": "web/modules/custom/os2forms_rest_api/patches/webform_rest_submission.patch"
Rewrite to something along the lines of “… modify response data sent from …”.

2022-08-30 09:27 UTC, rimi-itk commented on web/modules/custom/os2forms_rest_api/README.md
> +To allow updating data received from calling Webform Submission GET,
Rewrite to something along the lines of “… modify response data sent from …”.

2022-08-30 09:27 UTC, rimi-itk commented on web/modules/custom/os2forms_rest_api/patches/webform_rest_submission.patch
> ++ * Class WebformSubmissionGetResponseEvent, an event to change the response from calling GET webform submission.
It may be worth stating that it's only the `data` value in the response we can modify.

2022-08-30 09:27 UTC, rimi-itk commented on web/modules/custom/os2forms_rest_api/src/EventSubscriber/WebformSubmissionEventSubscriber.php
> +    $this->loggerFactory = $loggerFactory;
Consider changing this to a `logger` property and setting it to `$loggerFactory->get('os2forms_rest_api`)` or [injecting a specific channel](https://www.drupal.org/docs/8/api/logging-api/overview#specific-channel).

2022-08-30 09:27 UTC, rimi-itk commented on web/modules/custom/os2forms_rest_api/src/EventSubscriber/WebformSubmissionEventSubscriber.php
> +            $this->loggerFactory->get('os2forms_rest_api')->warning(sprintf('Unhandled linked entity type %s', $linkedEntityType));
Getting the actual logger channel each time we need to log something will be easier if we have a `logger` property rather than a `loggerFactory` (cf. comment on the constructor).

2022-08-30 10:53 UTC, jekuaitk commented on web/modules/custom/os2forms_rest_api/src/EventSubscriber/WebformSubmissionEventSubscriber.php
> +    $this->loggerFactory = $loggerFactory;
Injected specific channel in 75e92ddee2e986c1eab07b8109fd96822043d7e7.

2022-08-30 10:53 UTC, jekuaitk commented on web/modules/custom/os2forms_rest_api/src/EventSubscriber/WebformSubmissionEventSubscriber.php
> +            $this->loggerFactory->get('os2forms_rest_api')->warning(sprintf('Unhandled linked entity type %s', $linkedEntityType));
Injected specific channel in 75e92ddee2e986c1eab07b8109fd96822043d7e7.

2022-08-30 11:05 UTC, jekuaitk commented on composer.json
> +                "Add ability to modify data received the Webform Submission endpoint": "web/modules/custom/os2forms_rest_api/patches/webform_rest_submission.patch"
Reworded to 'Addded ability to modify response data sent from Webform Submission endpoint'

2022-08-30 11:11 UTC, jekuaitk commented on web/modules/custom/os2forms_rest_api/README.md
> +To allow updating data received from calling Webform Submission GET,
Reworded.

2022-08-30 11:19 UTC, jekuaitk commented on web/modules/custom/os2forms_rest_api/patches/webform_rest_submission.patch
> ++ * Class WebformSubmissionGetResponseEvent, an event to change the response from calling GET webform submission.
Updated to state that it's only the `data` value that can be modified.

2022-08-30 11:32 UTC, jekuaitk commented on web/modules/custom/os2forms_rest_api/src/EventSubscriber/WebformSubmissionEventSubscriber.php
> +        $values = (array) $data[$name];
Added comment explaining.

2022-08-30 12:11 UTC, rimi-itk approved these changes

2022-08-30 13:25 UTC, merged