DW-454: Organisationsdata
itk-dev/os2forms_selvbetjening pull request #96
Opened 2022-11-17 09:19 UTC by jekuaitk

2022-11-21 15:04 UTC, rimi-itk requested changes
Nice job. Some changes and fixed needed:

* Use https://www.php.net/manual/en/book.dom.php to build and manipulate XML
* Be consistent on how to handle empty values (`NULL !== …`, `!…`, …)

Can we move the code for actually calling the organization API to https://github.com/itk-dev/serviceplatformen? Or if it's too much of a hazzle right now prepare it a bit for moving it  later?

2022-12-12 12:06 UTC, jekuaitk commented on config/sync/core.entity_form_display.user.user.default.yml
> +    third_party_settings: {  }
Will be handled later.

2022-12-12 12:06 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/README.md
> +```phpt
Fixed.

2022-12-12 12:09 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/os2forms_organisation.info.yml
> +core_version_requirement: ^8 || ^9
Nope, removed.

2022-12-12 12:10 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +      // @todo HANDLE PEOPLE WITH MORE THAN ONE FUKNTION?
Fixed typo. More than one employment will be handled next.

2022-12-12 12:12 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +    if ($id === NULL) {
Fixed.

2022-12-12 12:15 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +    $cvr = '55133018';
Moved to configuration.

2022-12-12 12:15 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +    $public_cert = file_get_contents(__DIR__ . '/../../' . $orgConfig->get('public_cert_location'));
Fixed.

2022-12-12 12:21 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/os2forms_organisation.services.yml
> +    class: Drupal\os2forms_organisation\Helper\Helper
Updated.

2022-12-12 12:24 UTC, jekuaitk commented on .gitignore
> +/web/modules/custom/os2forms_organisation/certificates
Removed as we now give path directly to certificates in configuration.

2022-12-12 13:30 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +    if (!$personId) {
Makes sense now that i use `PropertyAccessor`.

2022-12-12 13:30 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +    $responseArray = $this->brugerLaes($brugerId, $token);
Renamed.

2022-12-12 14:12 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +    return NULL;
Used ternary operator.

2022-12-12 14:31 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/OrganisationService.php
> +    return <<<XML
After many hours attempting to use DOM i have thrown in the towel - for now. Perhaps in the future we/i could attempt the refactoring.

Renamed to `build...XML`.

2022-12-14 09:18 UTC, rimi-itk requested changes

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Plugin/WebformElement/PersonAZIdentElement.php
> +    $instance->helper = \Drupal::getContainer()->get(Helper::class);
Why don't you use the container instance in `$container` here?

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Plugin/WebformElement/PersonEmailElement.php
> +    $instance->helper = \Drupal::getContainer()->get(Helper::class);
Why don't you use the container instance in `$container` here?

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Plugin/WebformElement/PersonLocationElement.php
> +    $instance->helper = \Drupal::getContainer()->get(Helper::class);
Why don't you use the container instance in `$container` here?

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Plugin/WebformElement/PersonMagistratElement.php
> +    $instance->helper = \Drupal::getContainer()->get(Helper::class);
Why don't you use the container instance in `$container` here?

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Plugin/WebformElement/PersonNameElement.php
> +    $instance->helper = \Drupal::getContainer()->get(Helper::class);
Why don't you use the container instance in `$container` here?

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Plugin/WebformElement/PersonOrganisationAddressElement.php
> +    $instance->helper = \Drupal::getContainer()->get(Helper::class);
Why don't you use the container instance in `$container` here?

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Plugin/WebformElement/PersonOrganisationEnhedElement.php
> +    $instance->helper = \Drupal::getContainer()->get(Helper::class);
Why don't you use the container instance in `$container` here?

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Plugin/WebformElement/PersonOrganisationToEnhedElement.php
> +    $instance->helper = \Drupal::getContainer()->get(Helper::class);
Why don't you use the container instance in `$container` here?

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Plugin/WebformElement/PersonPhoneElement.php
> +    $instance->helper = \Drupal::getContainer()->get(Helper::class);
Why don't you use the container instance in `$container` here?

2022-12-14 09:18 UTC, rimi-itk commented on .gitignore
> +!/web/modules/custom/os2forms_user_menu
This PR has nothing to do with “os2forms_user_menu” so “os2forms_user_menu” should not be mentioned here.

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +    return $value;
Rewrite to

```php
return implode('', array_map(static function ($key) { return '['.$key.']'; }, $keys);
```

or maybe

```php
return '['.implode('][', $keys).']';
```

2022-12-14 09:18 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +  private function convertKeysToPropertyAccessorFormat(array $keys): string {
Consider renaming to `arrayToPropertyPath`.

2022-12-15 08:08 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +  private function convertKeysToPropertyAccessorFormat(array $keys): string {
It may be worth adding a `getValue`, say, function to the class rather than calling `convertKeysToPropertyAccessorFormat` and `PropertyAccessor::getValue` in multiple places, i.e. replace

```php
return $this->propertyAccessor->getValue($data, $this->convertKeysToPropertyAccessorFormat($navnTekstKeys)) ?: '';
```

with

```php
return $this->getValue($data, $navnTekstKeys, '');

…

private function getValue(mixed $data, array $keys, $defaultValue = null) { … }
```

2022-12-15 12:52 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Plugin/WebformElement/PersonAZIdentElement.php
> +    $instance->helper = \Drupal::getContainer()->get(Helper::class);
Used `$container`.

2022-12-15 14:57 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +    return $value;
Updated.

2022-12-19 08:09 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +  private function convertKeysToPropertyAccessorFormat(array $keys): string {
Updated.

2022-12-19 08:57 UTC, rimi-itk requested changes
Some minor changes suggested.

2022-12-19 08:57 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Element/MineOrganisationsData.php
> +      '#title' => t('Name'),
If possible you should `use StringTranslationTrait` and use `$this->t` rather than the global `t` function.

2022-12-19 08:57 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +  }
Consider removing the `arrayToPropertyPath` function (that's only used in one place) and do the conversion inside `getValue`.

2022-12-19 08:57 UTC, rimi-itk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +    return $this->propertyAccessor->getValue($data, $this->arrayToPropertyPath($keys)) ?: $defaultValue;
Consider some error handling here and using `PropertyAccessor:: isReadable` to check if the requested path can be read.

2022-12-19 09:22 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Element/MineOrganisationsData.php
> +      '#title' => t('Name'),
`getCompositeElements` is static so this is not possible.

2022-12-19 09:28 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +  }
Removed.

2022-12-19 09:35 UTC, jekuaitk commented on web/modules/custom/os2forms_organisation/src/Helper/Helper.php
> +    return $this->propertyAccessor->getValue($data, $this->arrayToPropertyPath($keys)) ?: $defaultValue;
Checked if property is readable before attempting to get it.

2023-02-08 13:49 UTC, jekuaitk commented
Moved to https://github.com/itk-dev/os2forms_organisation

2023-02-08 13:49 UTC, closed without merging